### ISSUE TITLE
feat: implement body parsing

### ISSUE THREAD

**Issue by o-rumiantsev** [o-rumiantsev/special-fiesta#2]
Implement internal module, to parse request body according to content type

**Comment by KHYehor** [comment]
Are we going to use any lib here? according to this article,
https://ru.wikipedia.org/wiki/Список_MIME-типов there are really lots of content types...
It is going to be like a lib for this framework, isn't it?

**Comment by o-rumiantsev** [comment]
> Are we going to use any lib here? according to this article,
> [https://ru.wikipedia.org/wiki/Список_MIME-типов](https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_MIME-%D1%82%D0%B8%D0%BF%D0%BE%D0%B2) there are really lots of content types...
> It is going to be like a lib for this framework, isn't it?

@KHYehor Need to check, how koa-bodyparser works. Also it would be useful to consider how Impress(Metarhia) parses request body

**Comment by o-rumiantsev** [comment]
There is a minimal working implementation of body parsing, so it is not prior task. Should be implemented after MVP.
