### ISSUE TITLE
test: add load tests

### ISSUE THREAD

**Issue by o-rumiantsev** [o-rumiantsev/special-fiesta#3]
Add and run load tests. Compare performance with `koa`, `restify`, etc.

**Comment by KHYehor** [comment]
@o-rumiantsev  We have one task, this cool instrument https://github.com/mcollina/autocannon
is only for HTTP 1.1 :(
If we are going to use http 2, we need to find another way for testing it (I am looking for it now)

**Comment by o-rumiantsev** [comment]
> @o-rumiantsev We have one task, this cool instrument https://github.com/mcollina/autocannon
> is only for HTTP 1.1 :(
> If we are going to use http 2, we need to find another way for testing it (I am looking for it now)

@KHYehor no need in such lib. As far as currently we use http 1.1, like koa and others, we might compare only http performance for now.
