### ISSUE TITLE
feat: use http2 instead of http

### ISSUE THREAD

**Issue by o-rumiantsev** [o-rumiantsev/special-fiesta#4]

**Comment by KHYehor** [comment]
@o-rumiantsev, I guess we must do it as first step, because we need to account differences between http1.1 and http2, what do you think about this? Do they have like one abstract way to deal with them?
As I read http2 holds one connection not for each request and also have priorities for requests.

**Comment by KHYehor** [comment]
> @o-rumiantsev, I guess we must do it as first step, because we need to account differences

Also, how many user-agents today supports http2? Or we just do our lib on http2 and then user-agent question is not our problem?

**Comment by o-rumiantsev** [comment]
> @o-rumiantsev, I guess we must do it as first step, because we need to account differences between http1.1 and http2, what do you think about this? Do they have like one abstract way to deal with them?
> As I read http2 holds one connection not for each request and also have priorities for requests.

@KHYehor don't think so. For now the main objective is to compare performance over the same protocol with koa and co.

**Comment by o-rumiantsev** [comment]
> > @o-rumiantsev, I guess we must do it as first step, because we need to account differences
> 
> Also, how many user-agents today supports http2? Or we just do our lib on http2 and then user-agent question is not our problem?

As far as I know, most browsers by default try to use http2, but if server does not support it, it switches to http. By the way, we can add an option: use http or http2
